### ISSUE TITLE
API endpoints for diffs

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-db#42] opened 2017-05-11 18:43 UTC
Notes from a conversation:

web-monitoring-db will broker responses from "diffing services"

* `diff/start..end/` -> UNIX-style `diff`
* `diff/start..end/pf` -> PageFreezer JSON response
* maybe temporarily support `diff/start..end/versionista` but only versionista-source pages would support that

Response formatted as JSON. Maybe support richer types later.

```
{'page_id': ...,
 'version_id', ...,
 'diff_service': ...,
 'diff_service_version': ...,
 'content': VERBATIM_RESPONSE_FROM_DIFFING_SERVICE}
```

**Comment by Mr0grog** [comment] 2017-05-16 16:23
Oh, this is really a dupe of #8.

**Closed by Mr0grog** 2017-05-16 16:23 UTC
